version: '3'

services:

  api:
    container_name: api
    build: .
    ports:
      - "80:5000"
    depends_on: 
      - mongo

    links: 
      - mongo 
  
  mongo:
    container_name: db1
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    